[package]
name = "gridbugs-roguelike-tutorial-2022"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies.gridbugs]
version = "0.5"
features = [
    "chargrid",
    "chargrid_wgpu",
    "coord_2d",
]
